services:
  ollama:
    build:
      context: .
      dockerfile: dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - LLAMA_MODEL=${LLAMA_MODEL}

  nuxt-app:
    build: .
    container_name: nuxt-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/
      - NUXT_PUBLIC_LLAMA_MODEL=${LLAMA_MODEL}

volumes:
  ollama_data:
